// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/estimate-solar-system.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
import {
  centralSubsidyRates,
  solarIrradiance,
  stateSubsidies,
  stateTariffs
} from "npm:@/utils/solarSubsidyData";
var PANEL_WATTAGE = 0.4;
var SYSTEM_EFFICIENCY = 0.85;
var estimate_solar_system_default = defineTool({
  name: "estimate_solar_system",
  title: "Estimate rooftop solar system",
  description: "Quick estimate of solar system size (kW), cost, central + state subsidy, and year-1 monthly savings for a household in India.",
  inputSchema: {
    monthly_bill_inr: z.number().positive().describe("Average monthly electricity bill in INR."),
    state: z.string().describe("Indian state (e.g. 'Karnataka'). Use 'Other' if unknown."),
    shading_percent: z.number().min(0).max(100).default(10).describe("Estimated rooftop shading percentage (0-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ monthly_bill_inr, state, shading_percent }) => {
    const tariff = stateTariffs[state] ?? stateTariffs["Other"];
    const irradiance = solarIrradiance[state] ?? solarIrradiance["Other"];
    const shadingFactor = (100 - shading_percent) / 100;
    const monthlyConsumption = monthly_bill_inr / tariff;
    const dailyConsumption = monthlyConsumption / 30;
    const systemSize = Math.round(dailyConsumption / (irradiance * shadingFactor * SYSTEM_EFFICIENCY) * 100) / 100;
    const panels = Math.ceil(systemSize / PANEL_WATTAGE);
    const baseCostPerWatt = 55;
    const totalCost = Math.round(systemSize * 1e3 * baseCostPerWatt);
    let centralSubsidy = systemSize <= 3 ? systemSize * centralSubsidyRates.upTo3kW : 3 * centralSubsidyRates.upTo3kW + (systemSize - 3) * centralSubsidyRates.above3kW;
    centralSubsidy = Math.min(Math.round(centralSubsidy), 78e3);
    const stateInfo = stateSubsidies[state] ?? stateSubsidies["Other"];
    const stateSubsidy = stateInfo.rate > 0 ? Math.min(Math.round(totalCost * stateInfo.rate), stateInfo.maxAmount) : 0;
    const finalCost = totalCost - centralSubsidy - stateSubsidy;
    const annualGeneration = Math.round(
      systemSize * irradiance * 365 * shadingFactor * SYSTEM_EFFICIENCY
    );
    const monthlySavings = Math.round(
      Math.min(monthly_bill_inr * 0.85, annualGeneration / 12 * tariff)
    );
    const result = {
      system_size_kw: systemSize,
      panels,
      estimated_cost_inr: totalCost,
      central_subsidy_inr: centralSubsidy,
      state_subsidy_inr: stateSubsidy,
      final_cost_inr: finalCost,
      annual_generation_kwh: annualGeneration,
      monthly_savings_inr: monthlySavings,
      assumed_tariff_inr_per_kwh: tariff
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-state-subsidies.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
import { stateSubsidies as stateSubsidies2 } from "npm:@/utils/solarSubsidyData";
var list_state_subsidies_default = defineTool2({
  name: "list_state_subsidies",
  title: "List Indian state solar subsidies",
  description: "List rooftop-solar subsidy rates and caps for Indian states supported by Get A Solar. Optionally filter to one state.",
  inputSchema: {
    state: z2.string().optional().describe("Optional Indian state name (e.g. 'Karnataka'). Omit for all states.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ state }) => {
    const entries = Object.entries(stateSubsidies2).map(([name, info]) => ({
      state: name,
      rate_percent: Math.round(info.rate * 100),
      max_amount_inr: info.maxAmount,
      description: info.description
    }));
    const results = state ? entries.filter((e) => e.state.toLowerCase() === state.toLowerCase()) : entries;
    if (state && results.length === 0) {
      return {
        content: [{ type: "text", text: `No subsidy info found for state: ${state}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { subsidies: results }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "get-a-solar-mcp",
  title: "Get A Solar",
  version: "0.1.0",
  instructions: "Tools for Get A Solar, an Indian rooftop-solar bidding platform. Use `list_state_subsidies` to look up state-level solar subsidy rates and `estimate_solar_system` for a quick sizing/cost/savings estimate from a household's monthly electricity bill.",
  tools: [list_state_subsidies_default, estimate_solar_system_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
