// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/estimate-solar-system.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var centralSubsidyRates = { upTo3kW: 14588, above3kW: 7294 };
var stateSubsidies = {
  "Andhra Pradesh": { rate: 0.3, maxAmount: 2e4 },
  "Assam": { rate: 0.3, maxAmount: 3e4 },
  "Bihar": { rate: 0.5, maxAmount: 75e3 },
  "Chhattisgarh": { rate: 0.2, maxAmount: 2e4 },
  "Delhi": { rate: 0.2, maxAmount: 3e4 },
  "Gujarat": { rate: 0.5, maxAmount: 2e4 },
  "Haryana": { rate: 0.4, maxAmount: 4e4 },
  "Himachal Pradesh": { rate: 0.3, maxAmount: 1e4 },
  "Jharkhand": { rate: 0.5, maxAmount: 75e3 },
  "Karnataka": { rate: 0.2, maxAmount: 2e4 },
  "Kerala": { rate: 0.3, maxAmount: 15e3 },
  "Madhya Pradesh": { rate: 0.3, maxAmount: 3e4 },
  "Maharashtra": { rate: 0.25, maxAmount: 25e3 },
  "Odisha": { rate: 0.3, maxAmount: 3e4 },
  "Punjab": { rate: 0.3, maxAmount: 3e4 },
  "Rajasthan": { rate: 0.3, maxAmount: 3e4 },
  "Tamil Nadu": { rate: 0.25, maxAmount: 2e4 },
  "Telangana": { rate: 0.2, maxAmount: 2e4 },
  "Uttar Pradesh": { rate: 0.15, maxAmount: 3e4 },
  "Uttarakhand": { rate: 0.4, maxAmount: 4e4 },
  "West Bengal": { rate: 0.3, maxAmount: 3e4 },
  "Other": { rate: 0, maxAmount: 0 }
};
var solarIrradiance = {
  "Andhra Pradesh": 5.7,
  "Assam": 4.5,
  "Bihar": 5,
  "Chhattisgarh": 5.5,
  "Delhi": 5.2,
  "Gujarat": 6,
  "Haryana": 5.4,
  "Himachal Pradesh": 4.8,
  "Jharkhand": 5.2,
  "Karnataka": 5.8,
  "Kerala": 5,
  "Madhya Pradesh": 5.6,
  "Maharashtra": 5.5,
  "Odisha": 5.3,
  "Punjab": 5.1,
  "Rajasthan": 6.5,
  "Tamil Nadu": 5.5,
  "Telangana": 5.6,
  "Uttar Pradesh": 5,
  "Uttarakhand": 5.3,
  "West Bengal": 4.8,
  "Other": 5.2
};
var stateTariffs = {
  "Andhra Pradesh": 5.5,
  "Assam": 5.8,
  "Bihar": 5,
  "Chhattisgarh": 4.5,
  "Delhi": 5,
  "Gujarat": 4.5,
  "Haryana": 6,
  "Himachal Pradesh": 4,
  "Jharkhand": 5.5,
  "Karnataka": 6.5,
  "Kerala": 5.5,
  "Madhya Pradesh": 6,
  "Maharashtra": 8,
  "Odisha": 5,
  "Punjab": 5.5,
  "Rajasthan": 7,
  "Tamil Nadu": 4.5,
  "Telangana": 6,
  "Uttar Pradesh": 5.5,
  "Uttarakhand": 4.5,
  "West Bengal": 6.5,
  "Other": 5.5
};
var PANEL_WATTAGE = 0.4;
var SYSTEM_EFFICIENCY = 0.85;
var estimate_solar_system_default = defineTool({
  name: "estimate_solar_system",
  title: "Estimate rooftop solar system",
  description: "Quick estimate of solar system size (kW), cost, central + state subsidy, and year-1 monthly savings for a household in India.",
  inputSchema: {
    monthly_bill_inr: z.number().positive().describe("Average monthly electricity bill in INR."),
    state: z.string().describe("Indian state (e.g. 'Karnataka'). Use 'Other' if unknown."),
    shading_percent: z.number().min(0).max(100).default(10).describe("Estimated rooftop shading percentage (0-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ monthly_bill_inr, state, shading_percent }) => {
    const tariff = stateTariffs[state] ?? stateTariffs["Other"];
    const irradiance = solarIrradiance[state] ?? solarIrradiance["Other"];
    const shadingFactor = (100 - shading_percent) / 100;
    const monthlyConsumption = monthly_bill_inr / tariff;
    const dailyConsumption = monthlyConsumption / 30;
    const systemSize = Math.round(dailyConsumption / (irradiance * shadingFactor * SYSTEM_EFFICIENCY) * 100) / 100;
    const panels = Math.ceil(systemSize / PANEL_WATTAGE);
    const totalCost = Math.round(systemSize * 1e3 * 55);
    let centralSubsidy = systemSize <= 3 ? systemSize * centralSubsidyRates.upTo3kW : 3 * centralSubsidyRates.upTo3kW + (systemSize - 3) * centralSubsidyRates.above3kW;
    centralSubsidy = Math.min(Math.round(centralSubsidy), 78e3);
    const stateInfo = stateSubsidies[state] ?? stateSubsidies["Other"];
    const stateSubsidy = stateInfo.rate > 0 ? Math.min(Math.round(totalCost * stateInfo.rate), stateInfo.maxAmount) : 0;
    const finalCost = totalCost - centralSubsidy - stateSubsidy;
    const annualGeneration = Math.round(
      systemSize * irradiance * 365 * shadingFactor * SYSTEM_EFFICIENCY
    );
    const monthlySavings = Math.round(
      Math.min(monthly_bill_inr * 0.85, annualGeneration / 12 * tariff)
    );
    const result = {
      system_size_kw: systemSize,
      panels,
      estimated_cost_inr: totalCost,
      central_subsidy_inr: centralSubsidy,
      state_subsidy_inr: stateSubsidy,
      final_cost_inr: finalCost,
      annual_generation_kwh: annualGeneration,
      monthly_savings_inr: monthlySavings,
      assumed_tariff_inr_per_kwh: tariff
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-state-subsidies.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var stateSubsidies2 = {
  "Andhra Pradesh": { rate: 0.3, maxAmount: 2e4, description: "30% up to \u20B920,000" },
  "Assam": { rate: 0.3, maxAmount: 3e4, description: "30% up to \u20B930,000" },
  "Bihar": { rate: 0.5, maxAmount: 75e3, description: "50% up to \u20B975,000" },
  "Chhattisgarh": { rate: 0.2, maxAmount: 2e4, description: "20% up to \u20B920,000" },
  "Delhi": { rate: 0.2, maxAmount: 3e4, description: "\u20B92,000 per kW up to \u20B930,000" },
  "Gujarat": { rate: 0.5, maxAmount: 2e4, description: "\u20B910,000 per kW up to 2kW" },
  "Haryana": { rate: 0.4, maxAmount: 4e4, description: "40% up to \u20B940,000" },
  "Himachal Pradesh": { rate: 0.3, maxAmount: 1e4, description: "30% up to \u20B910,000" },
  "Jharkhand": { rate: 0.5, maxAmount: 75e3, description: "50% up to \u20B975,000" },
  "Karnataka": { rate: 0.2, maxAmount: 2e4, description: "20% up to \u20B920,000" },
  "Kerala": { rate: 0.3, maxAmount: 15e3, description: "30% up to \u20B915,000" },
  "Madhya Pradesh": { rate: 0.3, maxAmount: 3e4, description: "30% up to \u20B930,000" },
  "Maharashtra": { rate: 0.25, maxAmount: 25e3, description: "\u20B910,000 per kW up to 2.5kW" },
  "Odisha": { rate: 0.3, maxAmount: 3e4, description: "30% up to \u20B930,000" },
  "Punjab": { rate: 0.3, maxAmount: 3e4, description: "30% up to \u20B930,000" },
  "Rajasthan": { rate: 0.3, maxAmount: 3e4, description: "30% up to \u20B930,000" },
  "Tamil Nadu": { rate: 0.25, maxAmount: 2e4, description: "25% up to \u20B920,000" },
  "Telangana": { rate: 0.2, maxAmount: 2e4, description: "20% up to \u20B920,000" },
  "Uttar Pradesh": { rate: 0.15, maxAmount: 3e4, description: "\u20B915,000 per kW up to 2kW" },
  "Uttarakhand": { rate: 0.4, maxAmount: 4e4, description: "40% up to \u20B940,000" },
  "West Bengal": { rate: 0.3, maxAmount: 3e4, description: "30% up to \u20B930,000" }
};
var list_state_subsidies_default = defineTool2({
  name: "list_state_subsidies",
  title: "List Indian state solar subsidies",
  description: "List rooftop-solar subsidy rates and caps for Indian states supported by Get A Solar. Optionally filter to one state.",
  inputSchema: {
    state: z2.string().optional().describe("Optional Indian state name (e.g. 'Karnataka'). Omit for all states.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ state }) => {
    const entries = Object.entries(stateSubsidies2).map(([name, info]) => ({
      state: name,
      rate_percent: Math.round(info.rate * 100),
      max_amount_inr: info.maxAmount,
      description: info.description
    }));
    const results = state ? entries.filter((e) => e.state.toLowerCase() === state.toLowerCase()) : entries;
    if (state && results.length === 0) {
      return {
        content: [{ type: "text", text: `No subsidy info found for state: ${state}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { subsidies: results }
    };
  }
});

// src/lib/mcp/index.ts
var SUPABASE_URL = "https://vlkbfkfbpsawgusyabzt.supabase.co";
var mcp_default = defineMcp({
  name: "get-a-solar-mcp",
  title: "Get A Solar",
  version: "0.1.0",
  instructions: "Tools for Get A Solar, an Indian rooftop-solar bidding platform. Use `list_state_subsidies` to look up state-level solar subsidy rates and `estimate_solar_system` for a quick sizing/cost/savings estimate from a household's monthly electricity bill.",
  auth: auth.oauth.issuer({
    issuer: `${SUPABASE_URL}/auth/v1`,
    acceptedAudiences: "authenticated",
    jwksUri: `${SUPABASE_URL}/auth/v1/.well-known/jwks.json`
  }),
  tools: [list_state_subsidies_default, estimate_solar_system_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
