// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlkbfkfbpsawgusyabzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsa2Jma2ZicHNhd2d1c3lhYnp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzAyNjUsImV4cCI6MjA2MTg0NjI2NX0.qu6BAEUM8-YsAampoVXgxZiU1wXHDKh9gYM3lrrjgeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);